log_file = "./feedback.csv"
backup_file = "./feedback.bak"
cooldown_ms = 500

[template_context]
title = "Emoji-Feedback"
question = "Wie war das Hausaufgabentutorium heute?"
thanks = "Danke!"

[auth]
salt="subbh07uv0flGTz_C5lC6lag"
hash="j7pNzy-l_PD4TgMvG5umyQ1nZhlew4H2YZPB-WKgp-A="
