log_file = "./feedback.csv"
backup_file = "./feedback.bak"
cooldown_ms = 500

[template_context]
title = "Emoji feedback"
question = "How was your exercise today?"
thanks = "Thanks!"
acks = "Emoji icons supplied by EmojiOne. Fullscreen icon made by Freepik from www.flaticon.com. Thank you!"

[auth]
salt="subbh07uv0flGTz_C5lC6lag"
hash="j7pNzy-l_PD4TgMvG5umyQ1nZhlew4H2YZPB-WKgp-A="
